# Generated by Django 6.0.1 on 2026-02-22 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField()),
                ('target_value', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_habits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fast_kept', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('with_jamaat', models.BooleanField(default=False)),
                ('target_value', models.PositiveIntegerField(default=0)),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('text_input', models.CharField(blank=True, max_length=255, null=True)),
                ('day_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='main.daylog')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
